[id="con-screen_reader_testing_accessibility"]

= Screen reader testing

[role="_abstract"]
Testers use a screen reader to confirm that the experience parallels the results from manual testing and is equivalent to the intended design. This step ensures that the visual information on the screen is reinforced programmatically.

Screen readers are designed primarily for blind users, so there no need for a user interface. You turn a screen reader on, and it starts reading the content currently in focus.

Screen readers can be disorienting for sighted users at first, but with practice, you can get used to it.

Using a screen reader requires you to use basic keyboard shortcuts. Each screen reader has a different set of keyboard shortcuts, and the list of all available keystrokes is extensive; however, you can typically get by with just a handful of shortcuts.

The best way to learn how to use them is to pick one and learn the basic controls.

.Additional resources
* link:https://www.smashingmagazine.com/2019/02/accessibility-webinar/[How a screen reader accesses the web]
* link:https://techblog.wikimedia.org/2020/07/02/an-orca-screen-reader-tutorial/[Orca Screen Reader Tutorial] and link:https://help.gnome.org/users/orca/stable/commands.html.en#getting_started[Getting Started with Orca screen reader]
* link:https://webaim.org/articles/nvda/[Using NVDA to Evaluate Web Accessibility] and link:https://dequeuniversity.com/assets/pdf/screenreaders/nvda.pdf[NVDA Quick Reference Guide]
* link:https://www.apple.com/voiceover/info/guide/_1124.html[Learning VoiceOver Basics] and link:https://pauljadam.com/demos/iosvocheatsheet.html[iOS & VoiceOver Mobile Accessibility Cheat Sheet]
