[id="con-making_links_accessible"]

= Links

[role="_abstract"]
Screen readers announce links, and then read the link text. You don't need to do anything special to make that happen.

Screen reader users frequently navigate by links. Therefore, the link text should make sense when read out of context. Screen reader users often navigate from link to link by using the tab key (or shift + tab to go backwards through links). When navigating this way, only the link is read, not the rest of the sentence, so ambiguous links like "click here" or "more" are not helpful. Links like "products" or "about us" or "financial calculator" are more useful and more understandable.

* *Links Must Contain Text:* Links should not be empty. Screen readers may end up reading the link destination or some other piece of information (such as an image file name, if the only thing in a link is an image without alt text) if there is no text in the link. Sometimes that other information is helpful, but often it is not. It is better to provide meaningful text in the link.

* *Links Must Accurately Convey the Link Destination:* Ensure link text (and alternate text for images, when used as links) describes the destination or purpose of the link. If possible, the link text should make sense out of context of the words around it.
