[id="proc-manual_testing_accessibility"]

= Testing accessibility with a manual inspection

[role="_abstract"]
Manual accessibility testing uses keyboard, visual, and content tests to find issues that automated testing cannot.

Manual testing is divided into steps. A visual inspection is followed by pointer and keyboard checks. Testers then validate the ability of the content to resize. They complete manual testing by confirming the accessibility of interactions.

.Prerequisites
* An automated report free of *Violations* or issues that *Need Review*

.Procedure

. Navigate through your document using a keyboard and ensure the following:
+
* Tabbing order logical and intuitive
* Keyboard focus indicator is visible
* Pressing *Enter* or *Space bar* selects a specific item
* There are no keyboard traps
+
[NOTE]
====
A common problem is keyboard focus getting caught in controls and being unable to get out.
====
+
. Scan through the document and verify the contents against the xref:ref-concise-checklist[Accessibility checklist].

After testing is complete, violations should be reported such that they allow even those with little or no accessibility knowledge to fix the issue. Violations should be explained and guidance for remediation should be provided when possible.
