[id="con-making_content_accessible"]

= Making content accessible

[role="_abstract"]
Some aspects of web accessibility are of a technical nature, and they are handled by the Digital Experience (DX) team. The DX team takes care of fonts and colors, contrast ratios, creating form labels, providing keyboard accessibility, and so on. They are responsible for the framework of our online documentation.

We, however, are responsible for making our documentation content accessible. When creating content, there are a number of guidelines to follow to ensure your content is accessible:

* Use clear and simple language.
* Make *all* information available in text form. This means providing alternative text for images and links, providing descriptions of charts or graphs, and providing descriptions for instances of color, size, or shape-based information.
* Use correct asciidoc attributes and avoid getting creative with formatting.
* Do *not* skip heading levels or use simple bold formatting for headings.
* Table structure should be kept simple.
//For guidance on creating accessible tables, see link://https://source.redhat.com/groups/public/ccs/ccs_blog/accessibility_of_tables[Accessibility of tables].
* Do not use color or spatial position to convey information.

When you incorporate accessibility into your process, the result is stronger content for everyone.
