[id="con-making_images_accessible"]

= Images

[role="_abstract"]
Making images accessible is fundamental for accessibility compliance. All images must have a meaningful text alternative that serves the equivalent purpose of the image. The content of the alt text will vary based on the purpose of the image. The alt text should typically:

* Be accurate and equivalent in presenting the same content and function of the image.
* Be succinct. This means the correct content (if there is content) and function (if there is a function) of the image should be presented as succinctly as is appropriate. Typically, no more than a few words are necessary, though, rarely, a short sentence or two may be appropriate.
* Give blind users a functional equivalent or substitute for the image.
* Convey the purpose of the image — why you put the image in the document — rather than just the purely visual irrelevant aspects of the image.
Include any text which happens to be in the image.
* NOT be redundant or provide the same information as text within the context of the image.
* NOT use the phrases "image of ..." or "graphic of ..." to describe the image. It is usually apparent to the user that it is an image. And if the image is conveying content, it is typically not necessary that the user know that it is an image that is conveying the content, as opposed to text. If the fact that an image is a photograph or illustration, etc. is important content, it may be useful to include this in alternative text.
