[id="ref-concise-checklist"]

= CONCISE Accessibility checklist
Use the concise accessibility checklist as a quick reference to improve the accessibility of Red Hat product documentation.

.Concise accessibility checklist
[width=75,cols="90%,10%"]
|===
|Check for|Checked

a|*Images and Alternative Text*

    * Icons, images, diagrams, and non text elements have a meaningful alternative-text description.
    ** Icons - alt text describes what the icon does (not what the icon looks like)
    * Complex images such as charts, workflows, and graphs have descriptive text near the image.
    * The document does not contain images of text, for example, a screen capture image of an informational table.
| &#9744;

a|*Links and Hypertext*

    * URLs and cross-reference links have descriptive text that conveys information about the content of the linked target.
    * URLs are linked to correct and valid Web destinations.
| &#9744;

a|*Tables*

    * Tables have a simple, logical reading order from left to right, and top to bottom. Examples in the W3 accessibility guidelines.
    * Tables include a header row.
    * Avoid empty or blank table cells.
    * Header cells utilize the th tag and data cells utilize the td tag.
    * Tables are labeled with a caption.
| &#9744;
a|*Colors and other visual information*

    * Avoid instructions that rely solely on sensory characteristics. For example, do not use “Click the square, blue button to continue.”
    * Information is conveyed by methods and not by color alone.
    * There is sufficient contrast between foreground and background text or graphical elements in images and diagrams.
    * Instructions for navigating through an interface make sense without directional indicators such as left, right, above, and below.
| &#9744;

a|*Well-formed HTML and Meaningful Document Sequence*

    * Headings are correctly nested from H1 to H2, H3, and so forth, without skipping heading levels.
    * The correct Asciidoc tags are used to produce the intended HTML code.
| &#9744;
|===
